# Generated by Django 5.2 on 2025-04-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_usagecategory_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
