# Generated by Django 5.2 on 2025-04-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productvariant_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='initial_quantity',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0, help_text='재고 부족 경고 기준 수량'),
        ),
    ]
