# Generated by Django 5.2 on 2025-05-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_productvariant_initial_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('DONE', '완료')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PendingStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.pendingstockbatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.spec')),
            ],
        ),
    ]
