# Generated by Django 5.2 on 2025-05-22 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_pendingstockbatch_pendingstockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
            },
        ),
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'ordering': ['-timestamp'], 'verbose_name': '입출고 기록', 'verbose_name_plural': '입출고 기록'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '품목', 'verbose_name_plural': '품목'},
        ),
        migrations.AlterModelOptions(
            name='pendingstockbatch',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '입고 대기건', 'verbose_name_plural': '입고 대기건'},
        ),
        migrations.AlterModelOptions(
            name='pendingstockitem',
            options={'verbose_name': '입고 대기 품목', 'verbose_name_plural': '입고 대기 품목'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['item__name', 'spec__label'], 'verbose_name': '품목 규격', 'verbose_name_plural': '품목 규격'},
        ),
        migrations.AlterModelOptions(
            name='spec',
            options={'verbose_name': '규격', 'verbose_name_plural': '규격'},
        ),
        migrations.AlterModelOptions(
            name='usagecategory',
            options={'verbose_name': '사용처', 'verbose_name_plural': '사용처'},
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='사유'),
        ),
        migrations.AddField(
            model_name='pendingstockbatch',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='처리일시'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='일시'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='type',
            field=models.CharField(choices=[('IN', '입고'), ('OUT', '소모')], max_length=3, verbose_name='입출고 구분'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant', verbose_name='품목 규격'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.usagecategory', verbose_name='사용처'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='품목명'),
        ),
        migrations.AlterField(
            model_name='pendingstockbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('DONE', '완료'), ('CANCELED', '취소')], default='PENDING', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='pendingstockbatch',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='거래처'),
        ),
        migrations.AlterField(
            model_name='pendingstockbatch',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='pendingstockitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='품목'),
        ),
        migrations.AlterField(
            model_name='pendingstockitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='pendingstockitem',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.spec', verbose_name='규격'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='품목 코드'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='현재 재고'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='품목'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0, help_text='재고 부족 경고 기준 수량', verbose_name='안전 재고'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.spec', verbose_name='규격'),
        ),
        migrations.AlterField(
            model_name='spec',
            name='label',
            field=models.CharField(max_length=100, verbose_name='규격 라벨'),
        ),
        migrations.AlterField(
            model_name='usagecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='사용처 이름'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('item', 'spec')},
        ),
        migrations.AddField(
            model_name='pendingstockbatch',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryuser', verbose_name='처리자'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryuser', verbose_name='담당자'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
