# Generated by Django 5.2.4 on 2025-08-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, help_text='이 품목+규격의 단가(원)', verbose_name='단가'),
        ),
    ]
